[general]
animations=true
backend=fbdev
timeout=300

[input]
touchscreen=true
keyboard=true
pointer=false

[keyboard]
autohide=false
layout=us
popovers=true

[textarea]
obscured=true
#bullet=

[theme]
default=breezy-dark
alternate=breezy-light
